source "https://rubygems.org/"

gem 'sqlite3', '~> 1.4', '>= 1.4.4'
gem 'activerecord', '~> 7.0', '>= 7.0.3.1'
gem 'pry'
gem 'rake', '~> 13.0', '>= 13.0.6'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.25'